name: Compile 26Bar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ldid
        run: |
          brew install ldid

      - name: Set up Theos
        run: |
          git clone --quiet --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Set up iOS SDKs
        run: |
          rm -rf ~/theos/sdks
          git clone --quiet --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Compile 26Bar
        run: |
          cd 26Bar
          make clean
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload Compiled .deb
        uses: actions/upload-artifact@v4
        with:
          name: 26Bar-rootless-deb
          path: 26Bar/packages/*.deb
